export const locationSelect = {
  id: true,
  citizenId: true,
  type: true,
  governorate: true,
  town: true,
  street: true,
  block_number: true,
  house_number: true,
  latitude: true,
  longitude: true,
  notes: true,
  applicationId: true,
  createdAt: true,
  updatedAt: true,
} as const;
